# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Skipped'), (2, 'Shared')], default=0)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
